---
- name: provision AWS resources
  include: playbooks/provision-aws.yml

- name: install Ansible Tower
  hosts: tower-instance
  gather_facts: yes
  remote_user: ec2-user
  become: yes
  become_user: root
  roles:
    - name: tower
    - name: tower-demo-base
      when: configure_tower | default('no') | bool

- name: configure Ansible Tower
  hosts: tower-instance
  gather_facts: yes
  remote_user: ec2-user
  become: yes
  become_user: admin
  roles:
    - name: tower-demo-settings
      when: configure_tower | default('no') | bool
