---
- name: provision infrastructure
  include: provision-{{ target_platform }}.yml

- name: install ansible tower
  hosts: tower
  gather_facts: yes
  become: yes
  become_user: root
  roles:
    - name: tower
      when: install_tower | bool
    - name: tower-demo-base
      when: configure_tower_base | bool

- name: configure ansible tower
  hosts: tower
  gather_facts: no
  become: yes
  become_user: admin
  roles:
    - name: tower-demo-settings
      when: configure_tower | bool
