---
- name: provision AWS resources
  include: playbooks/provision-aws.yml

- name: install Ansible Tower
  hosts: tower-instance
  gather_facts: yes
  remote_user: ec2-user
  become: yes
  become_user: root
  roles:
    - tower
    - tower-demo-base

- name: configure Ansible Tower
  hosts: tower-instance
  gather_facts: yes
  remote_user: ec2-user
  become: yes
  become_user: admin
  roles:
    - tower-demo-settings
