---
- name: Add Amazon AWS Credentials
  tower_credential:  
    name: AWS Sales API Key
    description:  AWS API Key for Sales
    organization: Default
    config_file: ~/tower_cli.cfg
    kind: aws
    username: "{{ aws_access_key }}"
    password: ASK
    state: present

- name: Add Amazon SSH keys
  tower_credential:
    name: AWS SSH Key
    description:  AWS SSH Machine Key
    organization: Default
    config_file: ~/tower_cli.cfg
    kind: ssh
    username: "{{ aws_ssh_user }}"
    ssh_key_data: /root/lrich-key.pem
    state: present

- name: Add AWS Windows Password
  tower_credential:
    name: AWS Windows Password
    description: Windows Password for AWS machines
    organization: Default
    config_file: ~/tower_cli.cfg
    kind: ssh
    state: present
    username: Administrator
    password:  "{{ aws_windows_password }}"

- name: Add Tower Password
  tower_credential:
    name: Tower Password
    description: Password for Ansible Tower
    organization: Default
    config_file: ~/tower_cli.cfg
    kind: ssh
    ssh_key_data: ~/.ssh/id_rsa
    state: present
    username: root
    password:  "{{ vault_password }}"    
