---

- name: Add Ansible Teams
  include: teams.yaml
  
- name: Add Credentials to Tower
  include: credentials.yaml
  
- name: Add Projects to Tower
  include: projects.yaml
  
- name: Add Job-Templates to Tower
  include: job-templates.yaml 
