---
- name: create a demo aws keypair
  ec2_key:
    aws_access_key: "{{ ansible_aws_access_key }}"
    aws_secret_key: "{{ ansible_aws_secret_key }}"
    aws_region: "{{ ansible_aws_region }}"
    name: "{{ demo_keypair_name }}"
    key_material: "{{ demo_key.content | b64decode }}"
    state: present

- name: create the aws demo cloud credential
  tower_credential:
    config_file: ~/.tower_cli.cfg
    name: Demo Amazon Web Services
    description: AWS cloud credential used for shared demos.
    organization: Ansible Sales Demo
    kind: aws
    username: "{{ ansible_aws_access_key }}"
    password: "{{ ansible_aws_secret_key }}"
    state: present

- name: ensure all users have access to the demo cloud credential
  tower_role:
    config_file: ~/.tower_cli.cfg
    team: Sales Demo User
    role: use
    credential: Demo Amazon Web Services
    state: present
