---
- name: generate a demo ssh key
  shell: ssh-keygen -b 2048 -t rsa -f /home/admin/.ssh/demo_rsa -q -N ""
  args:
    creates: /home/admin/.ssh/demo_rsa

- name: grab the public key for the keypair
  slurp:
    src: /home/admin/.ssh/demo_rsa.pub
  register: demo_key

- name: create the demo machine credential
  tower_credential:
    config_file: ~/.tower_cli.cfg
    name: Demo SSH Key
    description: SSH key used for shared demos.
    organization: Ansible Sales Demo
    kind: ssh
    ssh_key_data: /home/admin/.ssh/demo_rsa
    state: present

- name: ensure all users have access to the demo machine credential
  tower_role:
    config_file: ~/.tower_cli.cfg
    team: Sales Demo User
    role: use
    credential: Demo SSH Key
    state: present

- name: create the demo admin machine credential
  tower_credential:
    config_file: ~/.tower_cli.cfg
    name: Demo Admin SSH Key
    description: SSH key used for shared demo administration.
    organization: Ansible Sales Demo
    kind: ssh
    username: admin
    ssh_key_data: /home/admin/.ssh/id_rsa
    state: present

- name: ensure all admins have access to the demo admin machine credential
  tower_role:
    config_file: ~/.tower_cli.cfg
    team: Sales Demo Admin
    role: use
    credential: Demo Admin SSH Key
    state: present
