---
sales_demo_teams:
    - name: Sales
    - name: Engineering
    - name: QA
    - name: DevOps
    - name: Sales Demo User
      description: Team with permissions to run all demos.
    - name: Sales Demo Admin
      description: Team with permissions to onboard new demo users.

sales_demo_projects:
  - name: Ansible Examples
    scm_url: https://github.com/wtcross/ansible-examples
    team_roles:
      - name: Sales Demo User
        type: update
      - name: Sales Demo User
        type: use
      - name: Sales Demo Admin
        type: admin

sales_demo_job_templates:
  - name: Provision LAMP HA Proxy Demo systems in AWS
    description: Launch the LAMP HA Proxy Demo systems in AWS
    job_type: run
    project: Ansible Examples
    playbook: lamp_haproxy/aws/demo-aws-launch.yml
    ask_inventory_on_launch: yes
    machine_credential: Demo SSH Key
    cloud_credential: Demo Amazon Web Services
    extra_vars: >
      ec2_image=ami-bc8131d4
      ec2_instance_count=2
      ec2_instance_type=m1.small
      ec2_keypair=ansible-sales-demo
      ec2_region={{ ansible_aws_region }}
    team_roles:
      - name: Sales Demo User
        type: execute
      - name: Sales Demo Admin
        type: admin
  - name: Deploy LAMP HA Proxy to Amazon Web Services
    description: Deploy an entire LAMP and HA Proxy environment to AWS
    job_type: run
    project: Ansible Examples
    playbook: lamp_haproxy/aws/site.yml
    ask_inventory_on_launch: yes
    machine_credential: Demo SSH Key
    cloud_credential: Demo Amazon Web Services
    limit: tag_ansible_group_webservers,tag_ansible_group_dbservers,tag_ansible_group_lbservers,tag_ansible_group_monitoring
    extra_vars: >
      repository=https://github.com/thisdavejohnson/mywebapp.git
      webapp_version=874944f067c540d336d2b85ad69d5decd0cba2f1
    team_roles:
      - name: Sales Demo User
        type: execute
      - name: Sales Demo Admin
        type: admin
  - name: Terminate Demo Instances
    description: "Shut down and delete a user's demo instances in AWS by Tower username"
    job_type: run
    project: Sandbox
    playbook: demo-aws-delete.yml
    ask_inventory_on_launch: yes
    machine_credential: Demo SSH Key
    cloud_credential: Demo Amazon Web Services
    limit: tag_ansible_group_webservers,tag_ansible_group_dbservers,tag_ansible_group_lbservers,tag_ansible_group_monitoring
    team_roles:
      - name: Sales Demo User
        type: execute
      - name: Sales Demo Admin
        type: admin
