# {{ ansible_managed }}
---
- hosts: sales-demo.ansible.com
  gather_facts: no
  become: no
  tasks:
    - name: Create the user
      shell: >
        tower-cli user create
        --first-name "{{ first_name }}"
        --last-name "{{ last_name }}"
        --username "{{ username }}"
        --email "{{ email }}"
        --password CHANGE_ME

    - name: Associate the user with the demo organization
      shell: >
        tower-cli organization associate
        --user "{{ username }}"
        --organization "Ansible Sales Demo"

    - name: Associate the user with the sales team
      shell: >
        tower-cli team associate
        --user "{{ username }}"
        --team Sales

    - name: Create an inventory for the user
      shell: >
        tower-cli inventory create
        --name "{{ username }}'s demo inventory"
        --description "Personal demo inventory for {{ username }}"
        --organization "Ansible Sales Demo"

    - name: Create an EC2 host group in each users inventory
      shell: >
        tower-cli group create
        --name aws-{{ ansible_aws_region }}
        --inventory "{{ username }}'s demo inventory"
        --credential "Demo Amazon Web Services"
        --source ec2
        --source-regions {{ ansible_aws_region }}
        --instance-filters "tag:Name=demo_{{ username }}"
        --overwrite true
        --overwrite-vars true
        --update-on-launch true

    - name: Ensure the user has access to their own inventory
      shell: >
        tower-cli role grant
        --inventory "{{ username }}'s demo inventory"
        --user "{{ username }}"
        --type "{{ item }}"
      with_items:
        - [ 'use', 'adhoc', 'update' ]
